version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: loopback-sample-api
    volumes:
      - .:/home/node/code
    ports:
      - 3000:3000
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - .:/app
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=datastore
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
